#! /usr/bin/perl

use 5.008;
use strict;
use warnings;
use Pod::Usage;

use App::Cosmic::Server;

our $VERSION = '0.01';

pod2usage(1)
    unless @ARGV;
pod2usage(0)
    if $ARGV[0] eq '--help';
print "$VERSION\n"
    if $ARGV[0] eq '--version';

my $cmd = shift @ARGV;
if ($cmd =~ /^(?:start|list|create|remove|change-credentials)$/) {
    $cmd =~ s/-/_/g;
    App::Cosmic::Server->instantiate->$cmd;
} else {
    die "unknown command: $cmd";
}

__END__

=head1 NAME

cosmic-server - Cosmic server implementation using iSCSI Enterprise Target

=head1 SYNOPSIS

  # setup iSCSI targets
  /etc/init.d/iscsitarget start
  cosmic-server start

  # stop iscsi targets
  /etc/init.d/iscsitarget stop

  # internal: create new volume
  cosmic-server create <global-name> <size>

  # internal: change credentials
  cosmic-server change-credentials <global-name> <username> <password>

  # internal: remove disk
  cosmic-server remove <global-name>

=head1 AUTHOR

Copypright (C) 2010 Cybozu Labs, Inc., written by Kazuho Oku

=head1 LICENSE

BSD License

=cut
