#! /usr/bin/perl

use 5.008;
use strict;
use warnings;
use Pod::Usage;

use App::Cosmic::Client;

our $VERSION = '0.01';

pod2usage(1)
    unless @ARGV;
pod2usage(0)
    if $ARGV[0] eq '--help';
print "$VERSION\n"
    if $ARGV[0] eq '--version';

my $cmd = shift @ARGV;
if ($cmd =~ /^(?:create|remove|connect|disconnect)$/) {
    App::Cosmic::Client->$cmd;
} else {
    die "unknown command: $cmd";
}

__END__

=head1 NAME

cosmic - a fail-safe network RAID

=head1 SYNOPSIS

  # create a new volume
  cosmic create global-name /dev/mdX 10G 10.0.0.1 10.0.0.2
  mkfs -t ext3 /dev/mdX
  mount /dev/mdX /var/mdX
  
  # connect to and mount an existing volume
  cosmic connect global-name /dev/mdX
  mount /dev/mdX /var/mdX
  
  # unmount and disconnect volume
  umount /var/mdX
  cosmic disconnect global-name /dev/mdX

  # remove a volume (should be run when disconnected)
  cosmic remove global-name

=head1 DESCRIPTION

Cosmic is a fail-safe network RAID, built around iSCSI.

=head1 AUTHOR

Copyright (C) 2010 Cybozu Labs, Inc., written by Kazuho Oku

=head1 LICENSE

BSD License

=cut
